improve testing_linux script

diff --git a/tools/testing/test_linux b/tools/testing/test_linux
--- a/tools/testing/test_linux
+++ b/tools/testing/test_linux
@@ -1,20 +1,44 @@
 #!/bin/bash
-set -e
+# set -e
 
+VerboseMode="true"
+ExitOnFirstFail="false"
 CompoundOutput=0
 
+##########
+
+BASH_SOURCE=pwd
 RepoRootDir="$(dirname "$BASH_SOURCE")/../.."
 echo $RepoRootDir
 
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(RepoRootDir)/lib
+export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RepoRootDir/lib
+
 for test in ./bin/test_*;
 do
   # Run all tests and call gcov on all cpp files after each test run. Then upload to codecov for every test run.
   # Codecov is able to process multiple uploads and merge them as soon as the CI job is done.
-  echo ">> Starting $test"
-  $test
-  if [ $? -eq 0 ];
+  if [ $VerboseMode == "false" ];
+  then
+    $test &> /dev/null
+    lastReturnValue=$?
+  else
+    $test 
+    lastReturnValue=$?
+  fi
+
+  if [ $lastReturnValue -ne 0 ];
   then 
-    $CompoundOutput = $CompoundOutput + 1
+    CompoundOutput=$((CompoundOutput + 1))
+    echo ">> Test $test FAILED!   ******** "
+
+    if [ $ExitOnFirstFail == "true" ];
+    then
+      exit $lastReturnValue
+    fi
+
+  else
+    echo ">> Test $test is rock solid!"
   fi
 done
+
+exit $CompoundOutput
